<?php
require('/volume1/web/wordpress/wp-load.php');
if(!is_user_logged_in() OR !current_user_can('update_core')) wp_die("Authorization required!");
global $wpdb;
if(isset($_REQUEST['umm_confirm_restore'])):
$wpdb->query("DELETE FROM $wpdb->usermeta");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(1, 1, 'first_name', '')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(2, 1, 'last_name', '')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(3, 1, 'nickname', 'cshenkan')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(4, 1, 'description', '')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(5, 1, 'rich_editing', 'true')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(6, 1, 'comment_shortcuts', 'false')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(7, 1, 'admin_color', 'fresh')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(8, 1, 'use_ssl', '0')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(9, 1, 'show_admin_bar_front', 'true')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(10, 1, 'wp_capabilities', 'a:1:{s:13:\"administrator\";b:1;}')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(11, 1, 'wp_user_level', '10')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(12, 1, 'dismissed_wp_pointers', 'wp330_toolbar,wp330_saving_widgets,wp340_choose_image_from_library,wp340_customize_current_theme_link,wp350_media')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(13, 1, 'show_welcome_panel', '1')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(14, 1, 'wp_dashboard_quick_press_last_post_id', '3')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(15, 1, 'managenav-menuscolumnshidden', 'a:4:{i:0;s:11:\"link-target\";i:1;s:11:\"css-classes\";i:2;s:3:\"xfn\";i:3;s:11:\"description\";}')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(16, 1, 'metaboxhidden_nav-menus', 'a:3:{i:0;s:8:\"add-post\";i:1;s:12:\"add-post_tag\";i:2;s:15:\"add-post_format\";}')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(17, 2, 'first_name', 'Alex')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(18, 2, 'last_name', 'Shenkan')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(19, 2, 'nickname', 'ashenkan')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(20, 2, 'description', '')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(21, 2, 'rich_editing', 'true')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(22, 2, 'comment_shortcuts', 'false')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(23, 2, 'admin_color', 'fresh')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(24, 2, 'use_ssl', '0')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(25, 2, 'show_admin_bar_front', 'true')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(26, 2, 'wp_capabilities', 'a:1:{s:6:\"editor\";b:1;}')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(27, 2, 'wp_user_level', '7')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(28, 2, 'dismissed_wp_pointers', 'wp330_toolbar,wp330_saving_widgets,wp340_choose_image_from_library,wp340_customize_current_theme_link,wp350_media')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(29, 1, 'wp_user-settings', 'libraryContent=browse')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(30, 1, 'wp_user-settings-time', '1384495055')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(31, 3, 'first_name', 'Justin')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(32, 3, 'last_name', 'Cunngingham')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(33, 3, 'nickname', 'jc')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(34, 3, 'description', '')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(35, 3, 'rich_editing', 'true')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(36, 3, 'comment_shortcuts', 'false')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(37, 3, 'admin_color', 'fresh')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(38, 3, 'use_ssl', '0')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(39, 3, 'show_admin_bar_front', 'true')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(40, 3, 'wp_capabilities', 'a:1:{s:6:\"editor\";b:1;}')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(41, 3, 'wp_user_level', '7')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(42, 3, 'dismissed_wp_pointers', 'wp330_toolbar,wp330_saving_widgets,wp340_choose_image_from_library,wp340_customize_current_theme_link,wp350_media')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(43, 4, 'first_name', 'Nan')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(44, 4, 'last_name', 'Shenkan')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(45, 4, 'nickname', 'ndavidson')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(46, 4, 'description', '')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(47, 4, 'rich_editing', 'true')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(48, 4, 'comment_shortcuts', 'false')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(49, 4, 'admin_color', 'fresh')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(50, 4, 'use_ssl', '0')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(51, 4, 'show_admin_bar_front', 'true')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(52, 4, 'wp_capabilities', 'a:1:{s:6:\"editor\";b:1;}')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(53, 4, 'wp_user_level', '7')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(54, 4, 'dismissed_wp_pointers', 'wp330_toolbar,wp330_saving_widgets,wp340_choose_image_from_library,wp340_customize_current_theme_link,wp350_media')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(55, 1, 'meta-box-order_nav-menus', 'a:1:{s:4:\"side\";s:60:\"add-page,add-custom-links,add-post,add-category,add-post_tag\";}')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(56, 1, 'nav_menu_recently_edited', '10')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(57, 2, 'email_users_accept_notifications', 'true')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(58, 2, 'email_users_accept_mass_emails', 'true')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(59, 1, 'email_users_accept_notifications', 'true')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(60, 1, 'email_users_accept_mass_emails', 'true')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(61, 3, 'email_users_accept_notifications', 'true')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(62, 3, 'email_users_accept_mass_emails', 'true')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(63, 4, 'email_users_accept_notifications', 'true')");
$wpdb->query("INSERT INTO $wpdb->usermeta (umeta_id, user_id, meta_key, meta_value) VALUES(64, 4, 'email_users_accept_mass_emails', 'true')");
print('Restore complete.');
else:
print('<form action="#" method="post"><p>Are you sure you want to restore all user meta data to the backup version?</p><button type="submit">Yes</button><input type="hidden" name="umm_confirm_restore" value="1" /></form>');
endif;
?>